name: sandbox

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno --version
          deno run https://deno.land/std/examples/welcome.ts
