name: sandbox

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno --version
          deno run --allow-net=randomuser.me ${GITHUB_WORKSPACE}/src/runHttp.ts https://randomuser.me/api/
